# Generated by Django 5.2.17 on 2026-10-01 04:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('priority', 'Priority'), ('urgent', 'Urgent')], max_length=16)),
                ('urgency_confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('checked_in', 'Checked in'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('no_show', 'No-show'), ('cancelled', 'Cancelled')], default='booked', max_length=16)),
                ('queue_date', models.DateField()),
                ('queue_number', models.PositiveIntegerField()),
                ('tracking_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinics.doctor')),
                ('intake', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='intake.intakesubmission')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinics.timeslot')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinics.specialty')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.patient')),
            ],
            options={
                'ordering': ['slot__start'],
                'indexes': [models.Index(fields=['doctor', 'queue_date', 'status'], name='appointment_doctor__0ea5ef_idx')],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'queue_date', 'queue_number'), name='unique_queue_number_per_doctor_day'), models.UniqueConstraint(condition=models.Q(('status__in', ['booked', 'checked_in', 'in_progress'])), fields=('slot',), name='one_active_appointment_per_slot')],
            },
        ),
    ]
