# Generated by Django 5.2.17 on 2026-10-01 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('avg_consultation_minutes', models.PositiveSmallIntegerField(default=20)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='clinics.clinic')),
            ],
            options={
                'verbose_name_plural': 'specialties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('room', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('current_delay_minutes', models.PositiveSmallIntegerField(default=0)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='clinics.clinic')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='clinics.specialty')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='clinics.doctor')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.AddConstraint(
            model_name='specialty',
            constraint=models.UniqueConstraint(fields=('clinic', 'code'), name='unique_specialty_code_per_clinic'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['doctor', 'start'], name='clinics_tim_doctor__7d9986_idx'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('doctor', 'start'), name='unique_slot_start_per_doctor'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='slot_end_after_start'),
        ),
    ]
