# Generated by Django 5.2.17 on 2026-10-08 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField()),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('priority', 'Priority'), ('urgent', 'Urgent')], max_length=20)),
                ('reasons', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='clinics.clinic')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.specialty')),
            ],
        ),
    ]
