# Generated by Django 5.2.17 on 2026-10-01 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_version', models.PositiveSmallIntegerField()),
                ('answers', models.JSONField()),
                ('suggested_urgency', models.CharField(choices=[('routine', 'Routine'), ('priority', 'Priority'), ('urgent', 'Urgent')], max_length=16)),
                ('urgency_score', models.PositiveSmallIntegerField(default=0)),
                ('reasons', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='clinics.clinic')),
                ('suggested_specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clinics.specialty')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
